wormhole-foundation/wormhole-dashboard

- src/components/Alerts.tsx
The new "Guardians not running the latest release" alert was missing from the tooltip
> update alert info

- .github/workflows/build.yaml
- .github/workflows/test.yaml
- config-overrides.js
- package-lock.json
- package.json
In looking at this dashboad live, I noticed it said:
1 guardian [XYZ] is down on Unknown (28)!
So I saw that chainId 28 was Xpla and this app is using the version of the sdk before Xpla was supported. This allows the dashboard to support Xpla and Aptos, both of which are in mainnet now.
This was updated automatically via this command:
npm install @certusone/wormhole-sdk@0.8.0
With these versions:
$ npm version
{
'wormhole-dashboard': '0.1.0',
npm: '8.5.2',
node: '17.7.1',
v8: '9.6.180.15-node.15',
uv: '1.43.0',
zlib: '1.2.11',
brotli: '1.0.9',
ares: '1.18.1',
modules: '102',
nghttp2: '1.47.0',
napi: '8',
llhttp: '6.0.4',
openssl: '3.0.1+quic',
cldr: '40.0',
icu: '70.1',
tz: '2021a3',
unicode: '14.0',
ngtcp2: '0.1.0-DEV',
nghttp3: '0.1.0-DEV'
}
Fixes #45
> Update wormhole-sdk to 0.8.0 for Xpla and Aptos

- watcher/src/consts.ts
- watcher/src/watchers/ArbitrumWatcher.ts
Changed the RPC.  The arbitrum RPC seems to do a better job of keeping up.
Also, through testing it seems that we can send requests for 25 blocks.  At 25 blocks, we sometimes get a 429.  But backing off 1 second seems to clear it up.
> watcher: change arbitrum RPC

- watcher/src/watchers/EVMWatcher.ts
- watcher/src/watchers/__tests__/EVMWatcher.test.ts
This code handles the following from Karura:
```
{
id: '0',
jsonrpc: '2.0',
error: {
code: 6969,
message: 'Error: No response received from RPC endpoint in 60s'
}
},
```
> watcher: handle karura code 6969

- watcher/src/watchers/EVMWatcher.ts
- watcher/src/watchers/__tests__/EVMWatcher.test.ts
Sometimes Karura will reply with a null block on a perfectly valid block number.  We need to handle that.
Request:
```
{
jsonrpc: '2.0',
id: '1',
method: 'eth_getBlockByNumber',
params: [ '0x461e9d', false ]
}
```
Response:
```
{ id: '1', jsonrpc: '2.0', result: null } 
```
> Karura null blocks

- dashboard/src/utils/explorer.ts
Correct explorer URL appears to be `https://suiexplorer.com/checkpoint/${block}`.
> Fix Sui transaction block link

- watcher/scripts/backfillNear.ts
For some reason, the Near rpc reduced the size of a batch.
Also, added some log messages that were useful during debugging.
> watcher/scripts: reduce near batchsize

- watcher/src/watchers/TerraExplorerWatcher.ts
- watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts
- watcher/src/watchers/__tests__/EVMWatcher.test.ts
Due to the recent changes on terra classic, the watcher needed to be changed.
> watcher: terra classic change

- watcher/scripts/backfillNear.ts
- watcher/src/utils/near.ts
- watcher/src/watchers/NearArchiveWatcher.ts
Near was having some errors that were only getting logged to console.error.  They need to be propagated up so that the error messages can get into Loki.  This PR makes those changes.
> watcher: change logging on near

- watcher/src/utils/isBase64Encoded.ts
- watcher/src/watchers/CosmwasmWatcher.ts
- watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts
Some cosmwasm chains are using base64 encoding and some are not.  This PR allows for both.
> watcher: add checks for base64 in cosmwasm

- cloud_functions/src/alarmMissingVaas.ts
- cloud_functions/src/utils.ts
If a VAA in the reobserve collection has been signed, then it no longer needs to be reobserved.
> cloud_function: don't keep signed vaa

- cloud_functions/package.json
- cloud_functions/scripts/deploy.sh
- cloud_functions/src/alarmMissingVaas.ts
- cloud_functions/src/data/evmosRPCs.json
- cloud_functions/src/data/kujiraRPCs.json
- cloud_functions/src/data/osmosisRPCs.json
- cloud_functions/src/index.ts
- cloud_functions/src/types.ts
- cloud_functions/src/utils.ts
- cloud_functions/src/wormchainMonitor.ts
- cloud_functions/tsconfig.json
This PR adds the wormchain monitoring of IBC clients and will alert to slack or pager duty as needed.
The .json files were pulled from:
osmosis - https://github.com/cosmos/chain-registry/blob/master/osmosis/chain.json#L518
evmos - https://github.com/cosmos/chain-registry/blob/master/evmos/chain.json#L373
Kujira - https://github.com/cosmos/chain-registry/blob/master/kujira/chain.json#L235
> cloud_functions: add wormchainMonitor

- watcher/src/utils/near.ts
- watcher/src/watchers/NearArchiveWatcher.ts
Near can have gaps in block numbers.  So, if you are going to request a specific block number, be prepared to handle the case where it doesn't exist.
> watcher: handle near missing blocks

- cloud-functions/deploy.sh
I created and deployed parallel cloud functions using go 1.21.
https://console.cloud.google.com/functions/details/europe-west3/governor-configs-21?env=gen1&project=wormhole-message-db-mainnet&tab=metrics
https://console.cloud.google.com/functions/details/europe-west3/governor-status-21?env=gen1&project=wormhole-message-db-mainnet
https://console.cloud.google.com/functions/details/europe-west3/guardian-heartbeats-21?env=gen1&project=wormhole-message-db-mainnet
> cloud-functions: bump go version

- fly/cmd/fly/main.go
- fly/go.mod
- fly/go.sum
This PR removes some hard coded tunables and expects them to be in a .env file.
> fly: put tunables into .env file

- watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts
This PR fixes the injective watcher test because it is simply taking too long to run.  So, just chose a newer block.
> watcher: update injective test

- watcher/src/utils/environment.ts
- watcher/src/utils/logger.ts
This PR allows the splitting of the logs going to Loki into mainnet and testnet versions for easier viewing.
> watcher: add testnet to logger product

- cloud_functions/src/computeTvlTvm.ts
- cloud_functions/src/wormchainMonitor.ts
This PR updates the wormchain endpoints in the TS cloud functions.
> cloud_functions: update wormchain rpcs

- watcher/src/watchers/utils.ts
The terra lcd watcher can't keep up any longer.  Need to switch to explorer watcher.
> watcher: terra2 to use explorer watcher

- watcher/src/watchers/utils.ts
We don't need a specialized PolygonWatcher now that the chain supports finalized.
> Polygon now has finalized

- cloud_functions/package.json
- package-lock.json
Was having an error deploying without this. We should add it back for now.
> Add @certusone/wormhole-sdk dependency to cloud_functions

- cloud_functions/scripts/deploy.sh
There are some functions that belong in both mainnet and testnet and some belong in only mainnet.  This PR splits that up.
> cloud_functions: update deploy script

- common/src/explorer.ts
I did actually run the dashboard to make sure the explorer link showed up correctly and went to the correct location.
> dashboard: change explorer rpc

- dashboard/src/contexts/NetworkContext.tsx
P2P is now running a testnet node 🙂
> dashboard: add P2P testnet endpoint

- fly/cmd/historical_uptime/main.go
- fly/common/types.go
- fly/pkg/historical_uptime/helpers.go
Precompute chain height differences before pushing to prometheus. This makes it easier to group and reduce the metrics on Grafana side.
> historical_uptime: push precomputed chain height differences

- common/src/consts.ts
- common/src/solana.ts
- watcher/src/watchers/NTTSolanaWatcher.ts
- watcher/src/watchers/SolanaWatcher.ts
- watcher/src/watchers/Watcher.ts
set `this.NTT` to `true` to enable `getNttMessagesForBlocks` for solana ntt
> ntt_solana_watcher: fix watcher not invoking getNttMessagesForBlocks

- watcher/src/watchers/utils.ts
Switching watchers for now just to keep things running.  Opened up this issue to keep track of the need to fix the TerraExplorerWatcher: https://github.com/wormhole-foundation/wormhole-dashboard/issues/259
> watcher: change XPLA, Terra2 watcher

- common/src/explorer.ts
Since network is now Network and not a string, everything was falling into the testnet branch.
> common: fix exploreVaa url

- dashboard/package.json
- dashboard/src/components/Contracts.tsx
- dashboard/src/components/Main.tsx
- dashboard/src/index.tsx
- package-lock.json
Adds a new page to display core contract info starting with the current guardian set index. This can be useful for contributors and integrators to track during a guardian set upgrade. Note that currently Solana and Pythnet are not supported since the dashboard does not have an allocated Solana or Pythnet RPC to use (every other chain has public endpoint usable from a web page). A future PR may move this functionality into a cloud function so that this info can be provided and cached.
> Config page

- watcher/src/watchers/SuiWatcher.ts
Apparently, suix_queryEvents is returning duplicate digests where it hadn't before.  If there are duplicate digests in the sui_multiGetTransactionBlocks call, it throws with a duplicate input error.
> watcher: de-dup sui digest results

- watcher/src/watchers/SolanaWatcher.ts
The maximumBatchSize needs to be changed down to 1000 because the watcher was receiving ```413 Payload Too Large```
> watcher: change Solana maximumBatchSize

- cloud_functions/package.json
- package-lock.json
The result of `npm i --save-exact rpc-websockets@7.11.0 -w cloud_functions`, this fixes an issue where a breaking patch release of `rpc-websockets` kills the cloud_functions deploy which don't adhere to the package lock. Ideally that could be fixed, but this PR just aims to get things working as they were.
> cloud_functions: fix rpc-websockets

- cloud_functions/src/computeNTTRateLimits.ts
- cloud_functions/src/computeTotalSupplyAndLocked.ts
- cloud_functions/src/getNTTRateLimits.ts
- cloud_functions/src/getTotalSupplyAndLocked.ts
Before this env var `NETWORK` has to conform to the sdkv2 format for the NTT related functions. 
Adding this allows us to use full caps `NETWORK` like `MAINNET` and `TESTNET`. This is to standardize the `NETWORK` env var format across all cloud functions.
> cloud_functions: convert env var NETWORK to sdk Network

- database/fast-transfer-schema.sql
- watcher/src/fastTransfer/types.ts
- watcher/src/watchers/FTSolanaWatcher.ts
- watcher/src/watchers/__tests__/FTSolanaWatcher.test.ts
PR does a few things:
1. try to get auction from auction account 
- if auction account is closed, grab the `auction_history` which the auction is in
- if the auction <> auction history mapping is not indexed in the db, index the database 
- if the mapping is in db, use this pubkey to query the `auction_history` account
2. query `message_protocol` from `AuctionUpdated` event
3. tests
- query a closed auction 
- update `executeFastOrderCctp`  txHash
4. add a table to auction history mapping
> ft_watcher: parse auction history if auction is closed

- common/src/wormhole.ts
This export is preventing the cloud_functions from being deployed via scripts/deploy.sh.
> common: remove unused export

- cloud_functions/src/alarmMissingVaas.ts
The dashboard and the cloud_function weren't always identifying the same VAAs as missing.  This puts them in sync.
> cloud_functions: remove refTime check

- database/fast-transfer-schema.sql
- watcher/src/watchers/FTSolanaWatcher.ts
- watcher/src/watchers/__tests__/FTSolanaWatcher.test.ts
This PR does a few things:
- parses `settle_auction_none_*` 
- add error handling for when ankr rpc nodes throw `unsafeRes` error on devnet
- tests for parsing. we cannot find any transaction with `settle_auction_none_cctp` so we shall not add the test case for that yet.
> ft_watcher: parse settleAuctionNoneLocal

- common/src/queryContractSmart.ts
This fixes an error I was seeing in the mainnet dashboard from the prefix bytes being the equivalent to the ascii `{`. This adopts the proper solution of using an official library's value parsing while still maintaining a dependency-free implementation.
> common: fix queryContractSmart parsing

- common/src/solana.ts
- database/fast-transfer-schema.sql
- watcher/src/fastTransfer/swapLayer/parser.ts
- watcher/src/fastTransfer/types.ts
- watcher/src/watchers/FTEVMWatcher.ts
- watcher/src/watchers/FTSolanaWatcher.ts
- watcher/src/watchers/__tests__/FTEVMWatcher.test.ts
- watcher/src/watchers/__tests__/FTSolanaWatcher.test.ts
This PR links the redeem swaps in https://github.com/wormhole-foundation/wormhole-dashboard/pull/349 and the fast transfers executions to complete the lifecyle
How it works:
1. For CCTP fast transfers (where dest chains are EVM), matching engine (on Solana) will publish a fill VAA which will be used for redeeming the USDC on the EVM side.
2. For Local fast transfers (where dest chain is Solana), matching engine doesn't need to publish a fill VAA. Instead it creates a fast fill account on Solana which will be used to redeem USDC on Solana chain itself.
This is why `fill_id` can either be a vaa id or Solana account pubkey
> ft_watcher: add fill ids to link fast order execution and redeem swaps

- fly/cmd/heartbeats/main.go
- fly/cmd/prom_gossip/Dockerfile
- fly/cmd/prom_gossip/README.md
- fly/cmd/prom_gossip/compose.yml
- fly/cmd/prom_gossip/dashboards/gossip_metrics.json
- fly/cmd/prom_gossip/main.go
- fly/cmd/prom_gossip/prometheus.yml
- fly/cmd/prom_gossip/provisioning/dashboards/automatic.yml
- fly/cmd/prom_gossip/provisioning/datasources/automatic.yml
- fly/common/consts.go
The goal of this PR is to provide a utility which can provide active analytics of the gossip network. `fly/cmd/prom_gossip/main.go` does this by tracking prometheus metrics for the various gossip messages. The provided readme describes how to run a prometheus and grafana server to view the metrics and a provided dashboard.
Reviewers: please confirm that `docker compose up` and the resulting dashboard at [http://localhost:3000](http://localhost:3000) works for you (more detailed instructions in the readme).
> fly: add a prometheus gossip metrics utility

- watcher/src/watchers/EVMWatcher.ts
Not sure why this is a thing now.  But Ankr has reduced the allowed batch size for Klaytn.
> watcher: reduce Klaytn batch size

- common/src/solana.ts
- database/fast-transfer-schema.sql
- watcher/jest.config.json
- watcher/mock/api.devnet.solana.com/parsedAccountInfo_Uku7YHVYicxWEnM7WNvAHGB1yw1dBCGzKXVanC4TxRK.json
- watcher/mock/api.devnet.solana.com/parsedTransaction_39K8aHVDmyAjne6J4PBFkvmKZH9CQR9QpbmTFafeiTLxeWg5n5RgcRdX5AYhebLR9shiUHrDeqg4YSD1EhRZNpS1.json
- watcher/mock/api.devnet.solana.com/parsedTransaction_3Ufce773W4xgVsZiGBhSRPQssfaNdrEWeTBPLTnQSFZHsVx9ADaSN9yQBF6kcQMyDAoAnM3BVU88tQ2TbDZn1kUJ.json
- watcher/mock/api.devnet.solana.com/parsedTransaction_4yCcw8MJ1BokhPJM2fQC3BMfoezteM4MkaHLfjPrLG25AEW4EeNxcNsrgU3ECkwQ1sy3AKFseafxM2mfjdwbzo8x.json
- watcher/mock/api.devnet.solana.com/transaction_2EFLPdYpdJzeoe4HD4fNRWwphhy9HyEHFj3EQtY9agUPmQ5LjJkXFjEt5dnshS9sSTby9nN2QF9BaCbVyiBFGLxj.json
- watcher/mock/api.devnet.solana.com/transaction_32goGrEsPb6Kky65Z4wX6wswzjDbT9pBWs1HSZFsfWhxoA1fnSsoE9hJgtepPL8VyKQJUdRrfGWPrXCizDufArwR.json
- watcher/mock/api.devnet.solana.com/transaction_39K8aHVDmyAjne6J4PBFkvmKZH9CQR9QpbmTFafeiTLxeWg5n5RgcRdX5AYhebLR9shiUHrDeqg4YSD1EhRZNpS1.json
- watcher/mock/api.devnet.solana.com/transaction_3Ufce773W4xgVsZiGBhSRPQssfaNdrEWeTBPLTnQSFZHsVx9ADaSN9yQBF6kcQMyDAoAnM3BVU88tQ2TbDZn1kUJ.json
- watcher/mock/api.devnet.solana.com/transaction_4EWH6ZetTTjdYSbxqXddKNKLKDpBctELAhqChmkey2jwunZaj1Digj1fQxBMxtw6uhDeqkX3ev2vucu7jrexhWka.json
- watcher/mock/api.devnet.solana.com/transaction_4yCcw8MJ1BokhPJM2fQC3BMfoezteM4MkaHLfjPrLG25AEW4EeNxcNsrgU3ECkwQ1sy3AKFseafxM2mfjdwbzo8x.json
- watcher/mock/api.devnet.solana.com/transaction_eo2CugBsJ9Efbtg9TAiYyBvvZZsbh93ZZcLDxxjbmbEpZojCF8BDphVVrCjXtMkSLaP2EGQE5zSrjU4r6fxsxRP.json
- watcher/src/fastTransfer/consts.ts
- watcher/src/fastTransfer/swapLayer/parser.ts
- watcher/src/fastTransfer/swapLayer/solParser.ts
- watcher/src/fastTransfer/types.ts
- watcher/src/idls/swap_layer.json
- watcher/src/watchers/__tests__/fastTransfer/SolanaSwapLayerParser.test.ts
This PR adds the Solana Swap Layer parser - to parse the completion of Fast Transfer that ends on Solana.
This PR might seem big but actually 7,339 line of the code are from IDL and test mock data. There is no Devnet Swap Layer now so we would have to mock these data. 
We are parsing 6 complete ix: 
1. `complete_transfer_direct`
2. `complete_transfer_payload `
3. `complete_transfer_relay`
4. `complete_swap_direct`
5. `complete_swap_payload `
6. `complete_swap_relay`
and a `release_inbound` ix
`complete_*_payload` ix is for dApps building on top of swap layer. It uses `staged_inbound` as an intermediary account to store the payload, which is released by the `release_inbound`. Hence there is a need to parse this ix and link it back to the `complete_*_payload` via `staged_inbound` pubkey. …
> ft_watcher: sol swap layer

- fly/cmd/heartbeats/main.go
Minor tweak for handling of batch observations in the `heartbeats` tool. Although this tool will be replaced by the `prom_gossip` tool in most cases, it is still useful in the guardian load testing environment, so it is worth fixing.
> Fix for batches in heartbeats tool

- fly/cmd/historical_uptime/main.go
- fly/pkg/bigtable/cache.go
- fly/pkg/bigtable/message.go
- fly/pkg/bigtable/message_test.go
- fly/pkg/bigtable/observation.go
- fly/pkg/bigtable/operations.go
- fly/pkg/bigtable/test_setup.go
- fly/pkg/historical_uptime/process_observation.go
- fly/pkg/historical_uptime/process_observation_test.go
This PR batches observation for processing to reduce DB calls to bigtable, which is the main bottle neck of the performance for processing. This causes the buffer to max out utilisation and drop observations before we can even process them. 
High level:
1. whenever there is an observation, add to a batch.
2. whenever batch size reaches `batchLimit` (for now its 100) or every 5 seconds, process the batch
High level of batch processing:
1. If message does not exist in cache, grab from db and put it in cache. If not found in db assume we haven't seen it before and create a new one in cache.
2. Grab all observations related and put in cache. Check current observation against in-cache observations for deduplication. If not exist, add to cache
3. After every batch, flush these data to db and …
> hum: batch process obs

- fly/cmd/historical_uptime/main.go
- fly/pkg/bigtable/cache.go
- fly/pkg/bigtable/message.go
- fly/pkg/bigtable/message_test.go
- fly/pkg/bigtable/observation.go
- fly/pkg/bigtable/operations.go
- fly/pkg/bigtable/test_setup.go
- fly/pkg/historical_uptime/helpers.go
- fly/pkg/historical_uptime/process_observation.go
- fly/pkg/historical_uptime/process_observation_test.go
This PR fixes negative observation count in the historical uptime monitor. It seems like RockawayX is sending duplicated observations really quickly such that the bigtable checks are not catching them. Additional dedup logic is needed when calculating missing observations. 
This PR also:
- increases obsC buffer 
- add monitor to check on obsC buffer utilization
for further debugging for the dropped observations bug
> hum: fix negative missing observation count

- database/fast-transfer-schema.sql
- watcher/src/fastTransfer/swapLayer/parser.ts
- watcher/src/fastTransfer/types.ts
- watcher/src/utils/TokenInfoManager.ts
- watcher/src/watchers/FTEVMWatcher.ts
- watcher/src/watchers/__tests__/FTEVMWatcher.test.ts
This PR adds the logic to persist token info (decimals, name, symbol) for tokens seen on the Swap Layer. This info is required for the Looker dashboard. 
The logic on Solana shall be added when Swap Layer is deployed on Solana.
> ft_watcher: add logic to persist token info

- fly/cmd/historical_uptime/main.go
- fly/common/types.go
- fly/pkg/historical_uptime/helpers.go
This PR adds the `safe` and `finalized` height to prometheus metrics
> hum: add safe and finalized heights

- fly/cmd/historical_uptime/main.go
- fly/pkg/bigtable/operations.go
This PR does a few things:
- fixes missing observation bug where monitor cannot find unprocessed messages as message indexes weren't created in `FlushCache`. 
- logs the bulk mutation for more observability.
- updates `MAX_CHAIN_ID` to be the largest mainnet chain id.
> fix missing message index mutation 

- dashboard/src/contexts/NetworkContext.tsx
- dashboard/src/utils/consts.ts
- watcher/src/consts.ts
[Here's](https://guardian.mainnet.xlabs.xyz/v1/governor/enqueued_vaas) proof that the endpoint works.
> Add xLabs public RPC

- watcher/scripts/backfillArbitrum.ts
- watcher/scripts/locateMessageGaps.ts
- watcher/src/consts.ts
- watcher/src/watchers/AlgorandWatcher.ts
- watcher/src/watchers/AptosWatcher.ts
- watcher/src/watchers/CosmwasmWatcher.ts
- watcher/src/watchers/EVMWatcher.ts
- watcher/src/watchers/InjectiveExplorerWatcher.ts
- watcher/src/watchers/NearArchiveWatcher.ts
- watcher/src/watchers/NearWatcher.ts
- watcher/src/watchers/SeiExplorerWatcher.ts
- watcher/src/watchers/SolanaWatcher.ts
- watcher/src/watchers/SuiWatcher.ts
- watcher/src/watchers/TerraExplorerWatcher.ts
- watcher/src/watchers/Watcher.ts
- watcher/src/watchers/WormchainWatcher.ts
- watcher/src/watchers/__tests__/AlgorandWatcher.test.ts
- watcher/src/watchers/__tests__/AptosWatcher.test.ts
- watcher/src/watchers/__tests__/ArbitrumWatcher.test.ts
- watcher/src/watchers/__tests__/BaseWatcher.test.ts
- watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts
- watcher/src/watchers/__tests__/EVMWatcher.test.ts
- watcher/src/watchers/__tests__/OptimismWatcher.test.ts
- watcher/src/watchers/__tests__/SolanaWatcher.test.ts
- watcher/src/watchers/__tests__/SuiWatcher.test.ts
This PR addresses the Near explorer endpoint having a low amount of requests per day.  The code is more efficient to conserve these requests.
> watcher: make near archive watcher work

- watcher/src/watchers/CosmwasmWatcher.ts
- watcher/src/watchers/utils.ts
For some reason the Terra2 explorers aren't being updated to contain current information.  So, need to move the Terra2 watcher back to the Cosmwasm watcher.
> watcher: change Terra2 watcher

- common/src/consts.ts
- common/src/explorer.ts
- dashboard/package.json
- database/package.json
- package-lock.json
- package.json
- watcher/src/consts.ts
- watcher/src/index.ts
- watcher/src/watchers/EVMWatcher.ts
- watcher/src/watchers/utils.ts
The core is available [here](https://unichain-d7a86fxp.blockscout.com/address/0xCa1D5a146B03f6303baF59e5AD5615ae0b9d146D).
This PR also removes support for MonadDevnet which is now obsolete.
> Add Unichain mainnet support
