src/components/EnqueuedVAAChecker.tsx, src/hooks/useCloudGovernorInfo.ts
added getSignedVaaWithRetry call for cloud function network contexts in EnqueuedVaaChecker.tsx
=> components: added support for cloud function context

src/components/Accountant.tsx, src/components/Governor.tsx, src/components/MainnetGovernor.tsx, src/utils/consts.ts
Guardian info from https://github.com/wormhole-foundation/wormhole-networks/blob/master/mainnetv2/guardianset/v3.prototxt
=> accountant guardian signing progress

watcher/src/consts.ts, watcher/src/watchers/CosmwasmWatcher.ts, watcher/src/watchers/InjectiveExplorerWatcher.ts, watcher/src/watchers/TerraExplorerWatcher.ts, watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts, watcher/src/watchers/index.ts, watcher/src/watchers/utils.ts
Migrated from https://github.com/wormhole-foundation/wormhole-monitor/pull/95
=> watcher: change to Injective explorer rpc

dashboard/src/components/Alerts.tsx, dashboard/src/components/Chains.tsx, dashboard/src/contexts/NetworkContext.tsx
This "feels" wrong.  Should be a way to just get the currentNetwork.
So, leaving this as a draft until comments come in.
=> dashboard: update quorum calculation for testnet

watcher/src/watchers/SuiWatcher.ts
The sui watcher shouldn't return messages older than fromCheckpoint, otherwise it overwrites rows in the observed messages table
=> watcher: sui getMessagesForBlocks old checkpoints fix

watcher/src/watchers/CosmwasmWatcher.ts, watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts
This fix is for when Terra finder says there is no transaction in a block but the lcd says that there is...
=> Terra2: bad block fix

.github/workflows/test.yaml, package-lock.json, package.json, watcher/src/watchers/__tests__/EVMWatcher.test.ts, watcher/src/watchers/__tests__/NearWatcher.test.ts
Needed to set exact prettier version in order to maintain parity with github actions.
=> dashboard: update to newest prettier

package-lock.json, watcher/package.json, watcher/src/watchers/AlgorandWatcher.ts
This PR updates the algosdk package and makes the necessary change to accommodate it.
=> watcher: algorand update

common/src/consts.ts, database/scripts/updateTokenMetadata.ts, package-lock.json, package.json, watcher/src/consts.ts, watcher/src/index.ts, watcher/src/watchers/__tests__/BaseWatcher.test.ts, watcher/src/watchers/__tests__/EVMWatcher.test.ts, watcher/src/watchers/utils.ts
This should add base.  Did I miss anything?
=> watcher: add base

watcher/src/watchers/__tests__/ArbitrumWatcher.test.ts
=> watcher: add arbitrum test

common/src/consts.ts, watcher/src/consts.ts, watcher/src/watchers/CosmwasmWatcher.ts, watcher/src/watchers/__tests__/CosmwasmWatcher.test.ts, watcher/src/watchers/utils.ts
Add Sei to the CosmwasmWatcher
=> watcher: add sei

watcher/scripts/readVAAs.ts
an inefficient script for extreme searching situations
=> scripts: read VAAs

package-lock.json, watcher/package.json, watcher/src/utils/logger.ts
Added the winston-loki integration package so that log messages can be sent to loki.
=> watcher: add winston-loki integration

cloud_functions/src/alarmMissingVaas.ts
This PR Checks the latest observed block time on each chain (as collected by the watcher) and alarms (via slackbot) those chains that have fallen behind >= 24 hours.  It will only alarm a chain once per 24 hours.
=> cloud_functions: alarm chains falling behind

watcher/scripts/backfillNear.ts, watcher/src/databases/BigtableDatabase.ts, watcher/src/databases/utils.ts, watcher/src/types/near.ts, watcher/src/utils/near.ts, watcher/src/watchers/NearArchiveWatcher.ts, watcher/src/watchers/__tests__/NearWatcher.test.ts, watcher/src/watchers/utils.ts
This PR is using a different approach to get the Near watcher to catch up.
=> Near watcher to use backfill

common/src/explorer.ts
=> fix: set url for solana transactions to the storage account

cloud_functions/src/data/evmosRPCs.json, cloud_functions/src/data/kujiraRPCs.json
This PR changes the ordering of the Kujira RPCs so that the more reliable endpoints are first.
=> cloud_functions: update Kujira RPCs

watcher/src/watchers/__tests__/NearWatcher.test.ts
Checking to see if this fixes the tests
=> watcher: only one near watcher in tests

cloud_functions/scripts/deploy.sh
=> cloud_functions:  add check

cloud_functions/src/computeTvlTvm.ts
This PR creates an array for accountant endpoints.  This cloud function was failing during cloud scheduling.
=> cloud_functions: add URL array for getting accountant info

common/src/explorer.ts
This PR, also, rearranges the URLs by chainId so as to be consistent.
=> Update explorer URLs

watcher/src/consts.ts, watcher/src/watchers/Watcher.ts
Just update the BSC rpc and add a few debug logging statements.
=> watcher: change bsc rpc

watcher/src/consts.ts, watcher/src/watchers/SeiExplorerWatcher.ts
Addendum:  While this PR allows sei to work on the testnet dashboard, there is no functioning testnet to monitor.
=> Allow sei in testnet dashboard

dashboard/package.json, dashboard/src/components/Accountant.tsx, package-lock.json
Right now just displays rudimentary JSON like
```
{
"pending": [
{
"digest": "G6k00i4y3JChM6fn64tZBwvRWPK7fdtXjykdSuZ9nn4=",
"tx_hash": "0FWHMhkdGdBVtk56xRldYA2p74Fuam7x2eIanwWTqos=",
"signatures": "295201",
"guardian_set_index": 3,
"emitter_chain": 7
}
]
}
```
or
```
{
"committed": {
"data": {
"amount": "1383838221",
"token_chain": 4,
"token_address": "00000000000000000000000055d398326f99059ff775485246999027b3197955",
"recipient_chain": 4
},
"digest": "IbG2mreGdRt5I+WU5/KsZ9RPlwaud0dHazdum931KuE="
}
}
```
=> dashboard: simple accountant transfer search

watcher/src/watchers/NTTSolanaWatcher.ts, watcher/src/watchers/__tests__/NTTSolanaWatcher.test.ts
- debugged some inconsistent digests and implement fix
- implement tests to make sure digests are consistent
=> ntt_solana_watcher: fix calculated digest

fly/cmd/healthcheck/main.go
useful for checking if a guardian's public IP is reported correctly
=> healthcheck: log peer address info

fly/pkg/bigtable/message.go
- batch read rows by 1000 at a time to mitigate `ReadRowsRequest message too large` error
=> historical_uptime: batch read rows

dashboard/src/App.tsx, dashboard/src/components/Main.tsx, dashboard/src/contexts/NetworkContext.tsx, dashboard/src/contexts/SettingsContext.tsx
=> dashboard: use search param for network, fixes #181

watcher/src/NTTConsts.ts, watcher/src/watchers/NTTSolanaWatcher.ts, watcher/src/watchers/NTTWatcher.ts
I moved common code around so there isn't so much copy pasta.  That's why it looks like a lot of code changes.
=> watcher: add normalized amount to NTT evm

cloud_functions/src/computeTvlTvm.ts, dashboard/src/utils/consts.ts, dashboard/vite.config.ts
swap P2P for xLabs' wormchain endpoint.
=> dashboard: update gateway url

cloud_functions/package.json, cloud_functions/src/_sdk_circleIntegration.ts, dashboard/package.json, database/package.json, package-lock.json, package.json, watcher/package.json
Main goal was to remove @certusone/wormhole-sdk from imported packages.
=> package.json: clean up refs

watcher/src/workers/supervisor.ts
Add logging to verify the old workers are going away.
=> watcher: add supervisor debugging

cloud_functions/src/computeGuardianSetInfo.ts
This PR improves computeGuardianSetInfo so that it only takes as long as the slowest RPC call. This should be safe as the requests are all going to different RPCs.
=> cloud_functions: improve computeGuardianSetInfo

cloud_functions/src/computeNTTRateLimits.ts, common/src/evm.ts, common/src/solana.ts, common/src/utils.ts
This PR adds retry and logging for NTT related contract calls
=> cloud_functions: add retries to ntt related requests

watcher/package.json, watcher/scripts/watchFt.ts, watcher/src/fastTransfer/consts.ts
PR adds Swap Layer contract address for EVM and script for manual `FTWatcher` usage
=> ft_watcher: add evm swap_layer ca

database/fast-transfer-schema.sql
This PR adds a normalized `chains` table for name display
=> ft: add chains table

dashboard/package.json, database/package.json, package-lock.json, package.json, scripts/upd_sdk.sh
Monad wiped their devnet so we needed to redeploy the core contract, which gave us a new address.
=> Update Monad Devnet core address

watcher/src/fastTransfer/types.ts, watcher/src/idls/matching_engine.json, watcher/src/idls/token_router.json, watcher/src/types/matching_engine.ts, watcher/src/types/token_router.ts, watcher/src/utils/solana.ts, watcher/src/watchers/FTSolanaWatcher.ts, watcher/src/watchers/SolanaWatcher.ts, watcher/src/watchers/__tests__/FTSolanaWatcher.test.ts
The IDLs were copied from  https://github.com/wormhole-foundation/example-liquidity-layer/blob/main/solana/ts/src/idl/json/
=> watcher: FT update IDLs

fly/cmd/prom_gossip/Dockerfile
golang version bump for latest guardian dependencies
=> fly: update prom_gossip docker

package-lock.json, watcher/package.json, watcher/src/watchers/SuiWatcher.ts
https://linear.app/wormholelabs/issue/CORE-826/wormhole-dashboard-update-sui-dependency
=> watcher: upgrade Sui client

common/src/consts.ts, common/src/explorer.ts, watcher/src/consts.ts, watcher/src/index.ts
fix Mezo testnet explorer urls
=> add Mezo mainnet
